name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
      
    - name: run
      run: ./testchecker
